import customtkinter
from customtkinter import *

#Window Settings
root = CTk()
root.title("Scrappy")
root.iconbitmap('C:/Users/GameBoi/PycharmProjects/Scrappy 2.0/imgs/recycler.ico')
root.geometry("1020x520")
customtkinter.set_appearance_mode('dark')

# Button Group 1
trash = CTkButton(root, text="Tech Trash")
trash.place(relx=0.3, rely=0.2, anchor=CENTER)
laptop = CTkButton(root, text="Computer")
laptop.place(relx=0.45, rely=0.2, anchor=CENTER)
sheet = CTkButton(root, text="Sheet Metal")
sheet.place(relx=0.6, rely=0.2, anchor=CENTER)
metal_blade = CTkButton(root, text="Blade")
metal_blade.place(relx=0.3, rely=0.3, anchor=CENTER)
metal_pipe = CTkButton(root, text="Metal Pipe")
metal_pipe.place(relx=0.45, rely=0.3, anchor=CENTER)
gears = CTkButton(root, text="Gear")
gears.place(relx=0.6, rely=0.3, anchor=CENTER)
springs = CTkButton(root, text="Spring")
springs.place(relx=0.3, rely=0.4, anchor=CENTER)
smg = CTkButton(root, text="SMG Body")
smg.place(relx=0.45, rely=0.4, anchor=CENTER)
rfl = CTkButton(root, text="Rifle Body")
rfl.place(relx=0.6, rely=0.4, anchor=CENTER)
fse = CTkButton(root, text="Fuse")
fse.place(relx=0.3, rely=0.5, anchor=CENTER)
trp = CTkButton(root, text="Tarp")
trp.place(relx=0.45, rely=0.5, anchor=CENTER)
cam = CTkButton(root, text="Camera")
cam.place(relx=0.6, rely=0.5, anchor=CENTER)
rpe = CTkButton(root, text="Rope")
rpe.place(relx=0.3, rely=0.6, anchor=CENTER)
semi = CTkButton(root, text="Semi Body")
semi.place(relx=0.45, rely=0.6, anchor=CENTER)
kit = CTkButton(root, text="Sewing Kit")
kit.place(relx=0.6, rely=0.6, anchor=CENTER)
tank = CTkButton(root, text="Propane Tank")
tank.place(relx=0.45, rely=0.7, anchor=CENTER)

#Button Group 2
pick = CTkButton(root, text="Ice Pick")
pick.place(relx=0.3, rely=0.2, anchor=CENTER)
hammer = CTkButton(root, text="Salvaged Hammer")
hammer.place(relx=0.45, rely=0.2, anchor=CENTER)
salvage = CTkButton(root, text="Salvaged Axe")
salvage.place(relx=0.6, rely=0.2, anchor=CENTER)
hatchet = CTkButton(root, text="Metal Hatchet")
hatchet.place(relx=0.3, rely=0.3, anchor=CENTER)
pickaxe = CTkButton(root, text="Metal Pickaxe")
pickaxe.place(relx=0.45, rely=0.3, anchor=CENTER)
prim_pick = CTkButton(root, text="Stone Pickaxe")
prim_pick.place(relx=0.6, rely=0.3, anchor=CENTER)
prim_axe = CTkButton(root, text="Stone Axe")
prim_axe.place(relx=0.3, rely=0.4, anchor=CENTER)
jack = CTkButton(root, text="Jackhammer")
jack.place(relx=0.45, rely=0.4, anchor=CENTER)
chain = CTkButton(root, text="Chainsaw")
chain.place(relx=0.6, rely=0.4, anchor=CENTER)
shove = CTkButton(root, text="Shovel")
shove.place(relx=0.3, rely=0.5, anchor=CENTER)
light = CTkButton(root, text="Flashlight")
light.place(relx=0.45, rely=0.5, anchor=CENTER)



# Run Init
root.mainloop()
